# Generated by Django 3.2.25 on 2026-03-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
