# Generated by Codex on 2026-03-14

from django.db import migrations


def create_tables(apps, schema_editor):
    table_names = set(schema_editor.connection.introspection.table_names())
    model = apps.get_model("auth_api", "User")
    if model._meta.db_table not in table_names:
        schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RunPython(create_tables, migrations.RunPython.noop),
    ]
