# Generated by Django 3.2.25 on 2026-03-14 06:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('api_key', models.TextField(blank=True, db_column='apiKey', null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stat_id', models.IntegerField(db_column='statId', unique=True)),
                ('name', models.TextField()),
                ('sent', models.IntegerField()),
                ('hard_bounce', models.IntegerField(db_column='hardBounce')),
                ('soft_bounce', models.IntegerField(db_column='softBounce')),
                ('unique_openers', models.IntegerField(db_column='uniqueOpeners')),
                ('total_clicks', models.IntegerField(db_column='totalClicks')),
                ('unique_clickers', models.IntegerField(db_column='uniqueClickers')),
                ('unsubscribes', models.IntegerField()),
                ('complaints', models.IntegerField()),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'Campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Cluster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterInteractionSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sent', models.IntegerField(default=0)),
                ('open', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('soft_bounce', models.IntegerField(db_column='softBounce', default=0)),
                ('hard_bounce', models.IntegerField(db_column='hardBounce', default=0)),
                ('unique_open', models.IntegerField(db_column='uniqueOpen', default=0)),
                ('unique_click', models.IntegerField(db_column='uniqueClick', default=0)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'ClusterInteractionSummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomainInteractionSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.TextField()),
                ('sent', models.IntegerField(default=0)),
                ('open', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('soft_bounce', models.IntegerField(db_column='softBounce', default=0)),
                ('hard_bounce', models.IntegerField(db_column='hardBounce', default=0)),
                ('unique_open', models.IntegerField(db_column='uniqueOpen', default=0)),
                ('unique_click', models.IntegerField(db_column='uniqueClick', default=0)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'DomainInteractionSummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('sent', models.BooleanField()),
                ('hard_bounce', models.BooleanField(db_column='hardBounce')),
                ('soft_bounce', models.BooleanField(db_column='softBounce')),
                ('unique_open', models.BooleanField(db_column='uniqueOpen')),
                ('total_clicks', models.IntegerField(db_column='totalClicks')),
                ('unique_clicker', models.BooleanField(db_column='uniqueClicker')),
                ('unsubscribe', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'UserInteraction',
                'managed': False,
            },
        ),
    ]
