# Generated by Django 3.2.25 on 2026-03-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cluster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clusterinteractionsummary',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='domaininteractionsummary',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'managed': True},
        ),
    ]
