# Generated by Codex on 2026-03-14

from django.db import migrations


def create_tables(apps, schema_editor):
    table_names = set(schema_editor.connection.introspection.table_names())

    account = apps.get_model("campaign_api", "Account")
    campaign = apps.get_model("campaign_api", "Campaign")
    cluster = apps.get_model("campaign_api", "Cluster")
    user_interaction = apps.get_model("campaign_api", "UserInteraction")
    cluster_summary = apps.get_model("campaign_api", "ClusterInteractionSummary")
    domain_summary = apps.get_model("campaign_api", "DomainInteractionSummary")

    for model in (
        account,
        campaign,
        cluster,
        user_interaction,
        cluster_summary,
        domain_summary,
    ):
        if model._meta.db_table not in table_names:
            schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_api", "0002_auto_20260314_0632"),
    ]

    operations = [
        migrations.RunPython(create_tables, migrations.RunPython.noop),
    ]
