# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_api", "0003_create_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "Campaign" ADD COLUMN "accountId" bigint;',
                        'ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_accountId_fkey" '
                        'FOREIGN KEY ("accountId") REFERENCES "Account"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "Cluster" ADD COLUMN "accountId" bigint NOT NULL;',
                        'ALTER TABLE "Cluster" ADD CONSTRAINT "Cluster_accountId_fkey" '
                        'FOREIGN KEY ("accountId") REFERENCES "Account"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "UserInteraction" ADD COLUMN "campaignId" bigint NOT NULL;',
                        'ALTER TABLE "UserInteraction" ADD COLUMN "clusterId" bigint;',
                        'ALTER TABLE "UserInteraction" ADD CONSTRAINT "UserInteraction_campaignId_fkey" '
                        'FOREIGN KEY ("campaignId") REFERENCES "Campaign"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "UserInteraction" ADD CONSTRAINT "UserInteraction_clusterId_fkey" '
                        'FOREIGN KEY ("clusterId") REFERENCES "Cluster"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "UserInteraction" ADD CONSTRAINT "UserInteraction_campaignId_email_key" '
                        'UNIQUE ("campaignId","email");',
                        'ALTER TABLE "ClusterInteractionSummary" ADD COLUMN "campaignId" bigint NOT NULL;',
                        'ALTER TABLE "ClusterInteractionSummary" ADD COLUMN "clusterId" bigint NOT NULL;',
                        'ALTER TABLE "ClusterInteractionSummary" ADD CONSTRAINT "ClusterInteractionSummary_campaignId_fkey" '
                        'FOREIGN KEY ("campaignId") REFERENCES "Campaign"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "ClusterInteractionSummary" ADD CONSTRAINT "ClusterInteractionSummary_clusterId_fkey" '
                        'FOREIGN KEY ("clusterId") REFERENCES "Cluster"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "ClusterInteractionSummary" ADD CONSTRAINT "ClusterInteractionSummary_campaignId_clusterId_key" '
                        'UNIQUE ("campaignId","clusterId");',
                        'ALTER TABLE "DomainInteractionSummary" ADD COLUMN "campaignId" bigint NOT NULL;',
                        'ALTER TABLE "DomainInteractionSummary" ADD CONSTRAINT "DomainInteractionSummary_campaignId_fkey" '
                        'FOREIGN KEY ("campaignId") REFERENCES "Campaign"(id) '
                        'DEFERRABLE INITIALLY DEFERRED;',
                        'ALTER TABLE "DomainInteractionSummary" ADD CONSTRAINT "DomainInteractionSummary_campaignId_domain_key" '
                        'UNIQUE ("campaignId","domain");',
                    ],
                    reverse_sql=[
                        'ALTER TABLE "DomainInteractionSummary" DROP CONSTRAINT "DomainInteractionSummary_campaignId_domain_key";',
                        'ALTER TABLE "DomainInteractionSummary" DROP CONSTRAINT "DomainInteractionSummary_campaignId_fkey";',
                        'ALTER TABLE "DomainInteractionSummary" DROP COLUMN "campaignId";',
                        'ALTER TABLE "ClusterInteractionSummary" DROP CONSTRAINT "ClusterInteractionSummary_campaignId_clusterId_key";',
                        'ALTER TABLE "ClusterInteractionSummary" DROP CONSTRAINT "ClusterInteractionSummary_clusterId_fkey";',
                        'ALTER TABLE "ClusterInteractionSummary" DROP CONSTRAINT "ClusterInteractionSummary_campaignId_fkey";',
                        'ALTER TABLE "ClusterInteractionSummary" DROP COLUMN "clusterId";',
                        'ALTER TABLE "ClusterInteractionSummary" DROP COLUMN "campaignId";',
                        'ALTER TABLE "UserInteraction" DROP CONSTRAINT "UserInteraction_campaignId_email_key";',
                        'ALTER TABLE "UserInteraction" DROP CONSTRAINT "UserInteraction_clusterId_fkey";',
                        'ALTER TABLE "UserInteraction" DROP CONSTRAINT "UserInteraction_campaignId_fkey";',
                        'ALTER TABLE "UserInteraction" DROP COLUMN "clusterId";',
                        'ALTER TABLE "UserInteraction" DROP COLUMN "campaignId";',
                        'ALTER TABLE "Cluster" DROP CONSTRAINT "Cluster_accountId_fkey";',
                        'ALTER TABLE "Cluster" DROP COLUMN "accountId";',
                        'ALTER TABLE "Campaign" DROP CONSTRAINT "Campaign_accountId_fkey";',
                        'ALTER TABLE "Campaign" DROP COLUMN "accountId";',
                    ],
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="campaign",
                    name="account",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="accountId",
                        null=True,
                        on_delete=models.DO_NOTHING,
                        related_name="campaigns",
                        to="campaign_api.account",
                    ),
                ),
                migrations.AddField(
                    model_name="cluster",
                    name="account",
                    field=models.ForeignKey(
                        db_column="accountId",
                        on_delete=models.DO_NOTHING,
                        related_name="clusters",
                        to="campaign_api.account",
                    ),
                ),
                migrations.AddField(
                    model_name="userinteraction",
                    name="campaign",
                    field=models.ForeignKey(
                        db_column="campaignId",
                        on_delete=models.DO_NOTHING,
                        related_name="interactions",
                        to="campaign_api.campaign",
                    ),
                ),
                migrations.AddField(
                    model_name="userinteraction",
                    name="cluster",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="clusterId",
                        null=True,
                        on_delete=models.DO_NOTHING,
                        related_name="user_interactions",
                        to="campaign_api.cluster",
                    ),
                ),
                migrations.AddField(
                    model_name="clusterinteractionsummary",
                    name="campaign",
                    field=models.ForeignKey(
                        db_column="campaignId",
                        on_delete=models.DO_NOTHING,
                        related_name="cluster_summaries",
                        to="campaign_api.campaign",
                    ),
                ),
                migrations.AddField(
                    model_name="clusterinteractionsummary",
                    name="cluster",
                    field=models.ForeignKey(
                        db_column="clusterId",
                        on_delete=models.DO_NOTHING,
                        related_name="summaries",
                        to="campaign_api.cluster",
                    ),
                ),
                migrations.AddField(
                    model_name="domaininteractionsummary",
                    name="campaign",
                    field=models.ForeignKey(
                        db_column="campaignId",
                        on_delete=models.DO_NOTHING,
                        related_name="domain_interaction_summaries",
                        to="campaign_api.campaign",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="userinteraction",
                    unique_together={("campaign", "email")},
                ),
                migrations.AlterUniqueTogether(
                    name="clusterinteractionsummary",
                    unique_together={("campaign", "cluster")},
                ),
                migrations.AlterUniqueTogether(
                    name="domaininteractionsummary",
                    unique_together={("campaign", "domain")},
                ),
            ],
        ),
    ]
