from django.urls import path

from .views import (
    add_isp_view,
    click_stats_get_user_data_view,
    click_stats_import_view,
    cluster_data_by_campaign_view,
    country_view,
    domain_data_by_campaign_view,
    domain_view,
    esp_view,
    fetch_campaign_data_view,
    get_cluster_data_view,
    import_view,
    isp_view,
    mailcamp_clusters_view,
    mailcamp_fetch_user_data_id_view,
    ongage_event_date_data_view,
    ongage_event_status_view,
    ongage_events_name_data_view,
    ongage_events_view,
    ongage_get_esp_connection_view,
    ongage_matrix_view,
    ongage_segement_count_view,
    ongage_segments_view,
    sheet_data_view,
    spreadsheet_url_view,
    users_get_users_view,
    users_onboard_view,
    users_set_password_view,
)

urlpatterns = [
    path("mailcamp/clusters", mailcamp_clusters_view),
    path("mailcamp/clusters/", mailcamp_clusters_view),
    path("mailcamp/fetch-campaign-data", fetch_campaign_data_view),
    path("mailcamp/fetch-campaign-data/", fetch_campaign_data_view),
    path("mailcamp/get-cluster-data", get_cluster_data_view),
    path("mailcamp/get-cluster-data/", get_cluster_data_view),
    path("mailcamp/domain-data-by-campaign", domain_data_by_campaign_view),
    path("mailcamp/domain-data-by-campaign/", domain_data_by_campaign_view),
    path("mailcamp/cluster-data-by-campaign", cluster_data_by_campaign_view),
    path("mailcamp/cluster-data-by-campaign/", cluster_data_by_campaign_view),
    path("mailcamp/fetch-user-data-id", mailcamp_fetch_user_data_id_view),
    path("mailcamp/fetch-user-data-id/", mailcamp_fetch_user_data_id_view),
    path("ongage/matrix", ongage_matrix_view),
    path("ongage/matrix/", ongage_matrix_view),
    path("ongage/events", ongage_events_view),
    path("ongage/events/", ongage_events_view),
    path("ongage/event-date-data", ongage_event_date_data_view),
    path("ongage/event-date-data/", ongage_event_date_data_view),
    path("ongage/events-name-data", ongage_events_name_data_view),
    path("ongage/events-name-data/", ongage_events_name_data_view),
    path("ongage/segments", ongage_segments_view),
    path("ongage/segments/", ongage_segments_view),
    path("ongage/get-esp-connection", ongage_get_esp_connection_view),
    path("ongage/get-esp-connection/", ongage_get_esp_connection_view),
    path("ongage/event-status", ongage_event_status_view),
    path("ongage/event-status/", ongage_event_status_view),
    path("ongage/segement-count", ongage_segement_count_view),
    path("ongage/segement-count/", ongage_segement_count_view),
    path("segment-count", ongage_segement_count_view),
    path("segment-count/", ongage_segement_count_view),
    path("spreadsheet-url", spreadsheet_url_view),
    path("spreadsheet-url/", spreadsheet_url_view),
    path("import", import_view),
    path("import/", import_view),
    path("country", country_view),
    path("country/", country_view),
    path("esp", esp_view),
    path("esp/", esp_view),
    path("domain", domain_view),
    path("domain/", domain_view),
    path("isp", isp_view),
    path("isp/", isp_view),
    path("addIsp", add_isp_view),
    path("addIsp/", add_isp_view),
    path("users/get-users", users_get_users_view),
    path("users/get-users/", users_get_users_view),
    path("users/onborad", users_onboard_view),
    path("users/onborad/", users_onboard_view),
    path("users/set-password", users_set_password_view),
    path("users/set-password/", users_set_password_view),
    path("click-stats/get-user-data", click_stats_get_user_data_view),
    path("click-stats/get-user-data/", click_stats_get_user_data_view),
    path("click-stats/import", click_stats_import_view),
    path("click-stats/import/", click_stats_import_view),
    path("sheet-data", sheet_data_view),
    path("sheet-data/", sheet_data_view),
]
